local util = require("tzfn.util")

return function(c, s)
	return {
		ColorColumn = { bg = c.overlay },
		Conceal = { fg = c.muted },
		CurSearch = { fg = c.bg, bg = c.ylw2 },
		Cursor = { fg = c.bg, bg = c.fg },
		lCursor = { fg = c.bg, bg = c.fg },
		CursorColumn = { bg = c.overlay },
		-- CursorIM = {},
		CursorLine = { bg = c.overlay },
		CursorLineNr = { fg = c.subtle },
		-- DarkenedPanel = { },
		-- DarkenedStatusline = {},
		DiffAdd = { bg = c.grn, blend = 50 },
		DiffChange = { bg = c.blu, blend = 30 },
		DiffDelete = { bg = c.red, blend = 40 },
		DiffText = { bg = c.ylw2, blend = 30 },
		diffAdded = { link = "DiffAdd" },
		diffChanged = { link = "DiffChange" },
		diffRemoved = { link = "DiffDelete" },
		Directory = { fg = c.blu2, bold = s.bold },
		-- EndOfBuffer = {},
		ErrorMsg = { fg = c.red, bold = s.bold },
		FloatBorder = { fg = c.blu2, bg = c.surface },
		FloatTitle = { fg = c.blu2, bg = c.surface, bold = s.bold },
		FoldColumn = { fg = c.subtle },
		Folded = { fg = c.subtle },
		IncSearch = { link = "CurSearch" },
		LineNr = { fg = c.muted },
		MatchParen = { fg = c.blu, bg = c.blu, blend = 25 },
		ModeMsg = { fg = c.fg },
		MsgSeparator = { fg = c.fg, bg = c.surface },
		MoreMsg = { fg = c.blu2 },
		NonText = { fg = c.muted },
		Normal = { fg = c.fg, bg = c.bg },
		NormalFloat = { bg = c.surface },
		NormalNC = { fg = c.fg, bg = s.dim_inactive and c._nc or c.bg },
		NvimInternalError = { link = "ErrorMsg" },
		Pmenu = { fg = c.fg, bg = c.surface },
		PmenuMatch = { fg = c.ylw2, bg = c.surface },
		PmenuSel = { bg = c.overlay },
		PmenuMatchSel = { fg = c.ylw2, bg = c.overlay },
		PmenuSbar = { fg = c.fg, bg = c.hl3 },
		PmenuThumb = { fg = c.fg, bg = c.hl3 },
		ComplHintMore = { fg = c.ylw2 },
		Question = { fg = c.ylw2 },
		QuickFixLine = { fg = c.fg, bg = c.hl2, bold = true },
		-- RedrawDebugNormal = {},
		RedrawDebugClear = { fg = c.bg, bg = c.ylw2 },
		RedrawDebugComposed = { fg = c.bg, bg = c.grn },
		RedrawDebugRecompose = { fg = c.bg, bg = c.red },
		Search = { fg = c.fg, bg = c.ylw2, blend = 70 },
		SignColumn = { fg = c.muted },
		SpecialKey = { fg = c.muted },
		SpellBad = { sp = c.red2, undercurl = true },
		SpellCap = { sp = c.ylw2, undercurl = true },
		SpellLocal = { sp = c.blu2, undercurl = true },
		SpellRare = { sp = c.grn2, undercurl = true },
		StatusLine = { fg = c.subtle, bg = c.surface },
		StatusLineNC = { fg = c.muted, bg = c.surface },
		StatusLineTerm = { fg = c.subtle, bg = c.surface },
		StatusLineTermNC = { fg = c.bg, bg = c.grn, blend = 60 },
		Substitute = { link = "IncSearch" },
		TabLine = { fg = c.muted, bg = c.surface },
		TabLineFill = { bg = "NONE" },
		TabLineSel = { fg = c.bg, bg = c.blu, bold = s.bold },
		Title = { fg = c.blu2, bold = true },
		VertSplit = { fg = c.cyn },
		Visual = { bg = c.hl3 },
		VisualNOS = { bg = c.hl3 },
		WarningMsg = { fg = c.ylw2, bold = s.bold },
		-- Whitespace = {},
		WildMenu = { link = "IncSearch" },
		WinBar = { fg = c.subtle, bg = c.surface, blend = 60 },
		WinBarNC = { fg = c.muted, bg = c.surface, blend = 60 },
		WinSeparator = { fg = c.muted },

		DiagnosticError = { fg = c.red, undercurl = true },
		DiagnosticHint = { fg = c.blu2 },
		DiagnosticInfo = { fg = c.mgt2 },
		DiagnosticOk = { fg = c.grn2 },
		DiagnosticWarn = { fg = c.ylw2 },
		DiagnosticDefaultError = { link = "DiagnosticError" },
		DiagnosticDefaultHint = { link = "DiagnosticHint" },
		DiagnosticDefaultInfo = { link = "DiagnosticInfo" },
		DiagnosticDefaultOk = { link = "DiagnosticOk" },
		DiagnosticDefaultWarn = { link = "DiagnosticWarn" },
		DiagnosticFloatingError = { link = "DiagnosticError" },
		DiagnosticFloatingHint = { link = "DiagnosticHint" },
		DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
		DiagnosticFloatingOk = { link = "DiagnosticOk" },
		DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
		DiagnosticSignError = { link = "DiagnosticError" },
		DiagnosticSignHint = { link = "DiagnosticHint" },
		DiagnosticSignInfo = { link = "DiagnosticInfo" },
		DiagnosticSignOk = { link = "DiagnosticOk" },
		DiagnosticSignWarn = { link = "DiagnosticWarn" },
		DiagnosticUnderlineError = { sp = c.red, undercurl = true },
		DiagnosticUnderlineHint = { sp = c.blu2, undercurl = true },
		DiagnosticUnderlineInfo = { sp = c.mgt2, undercurl = true },
		DiagnosticUnderlineOk = { sp = c.grn2, undercurl = true },
		DiagnosticUnderlineWarn = { sp = c.ylw2, undercurl = true },
		DiagnosticVirtualTextError = { fg = c.red, bg = c.red, blend = 10 },
		DiagnosticVirtualTextHint = { fg = c.blu2, bg = c.cyn, blend = 10 },
		DiagnosticVirtualTextInfo = { fg = c.mgt2, bg = c.blu, blend = 10 },
		DiagnosticVirtualTextOk = { fg = c.grn2, bg = c.grn, blend = 10 },
		DiagnosticVirtualTextWarn = { fg = c.ylw2, bg = c.ylw, blend = 10 },

		Boolean = { fg = c.ylw2 },
		Character = { fg = c.grn3_1 },
		Comment = { fg = c.muted, italic = s.italic },
		Conditional = { fg = c.blu2 },
		Constant = { fg = c.ylw },
		Debug = { fg = c.ylw2 },
		Define = { fg = c.red },
		Delimiter = { fg = c.cyn2 },
		Error = { fg = c.red },
		Exception = { fg = c.blu2 },
		Float = { fg = c.ylw2 },
		Function = { fg = c.blu },
		Identifier = { fg = c.fg },
		Include = { fg = c.red },
		Keyword = { fg = c.cyn2, italic = s.italic },
		Label = { fg = c.blu2 },
		LspCodeLens = { fg = c.subtle },
		LspCodeLensSeparator = { fg = c.muted },
		LspInlayHint = { fg = c.muted, bg = c.muted, blend = 10 },
		LspReferenceRead = { bg = util.blend(c.hl2, c.overlay, 0.3) },
		LspReferenceText = { bg = util.blend(c.hl2, c.overlay, 0.3) },
		LspReferenceWrite = { bg = util.blend(c.hl2, c.overlay, 0.3) },
		Macro = { fg = c.red },
		Number = { fg = c.ylw2 },
		Operator = { fg = c.cyn2 },
		PreCondit = { fg = c.red },
		PreProc = { link = "PreCondit" },
		Repeat = { fg = c.blu2 },
		Special = { fg = c.ylw },
		SpecialChar = { link = "Special" },
		SpecialComment = { fg = c.ylw },
		Statement = { fg = c.blu2, bold = s.bold },
		StorageClass = { fg = c.mgt2 },
		String = { fg = c.grn3_1 },
		Structure = { fg = c.mgt2 },
		Tag = { fg = c.ylw },
		Todo = { fg = c.ylw2, bg = c.ylw2, blend = 20 },
		Type = { fg = c.mgt2 },
		TypeDef = { link = "Type" },
		Underlined = { fg = c.fg, underline = true },

		healthError = { fg = c.red },
		healthSuccess = { fg = c.grn },
		healthWarning = { fg = c.ylw2 },

		htmlArg = { fg = c.blu2 },
		htmlBold = { bold = s.bold },
		htmlEndTag = { fg = c.subtle },
		htmlH1 = { link = "markdownH1" },
		htmlH2 = { link = "markdownH2" },
		htmlH3 = { link = "markdownH3" },
		htmlH4 = { link = "markdownH4" },
		htmlH5 = { link = "markdownH5" },
		htmlItalic = { italic = s.italic },
		htmlLink = { link = "markdownUrl" },
		htmlTag = { fg = c.subtle },
		htmlTagN = { fg = c.fg },
		htmlTagName = { fg = c.blu },

		markdownDelimiter = { fg = c.subtle },
		markdownH1 = { fg = c.ylw2, bold = s.bold },
		markdownH1Delimiter = { link = "markdownH1" },
		markdownH2 = { fg = c.blu2, bold = s.bold },
		markdownH2Delimiter = { link = "markdownH2" },
		markdownH3 = { fg = c.blu, bold = s.bold },
		markdownH3Delimiter = { link = "markdownH3" },
		markdownH4 = { fg = c.mgt, bold = s.bold },
		markdownH4Delimiter = { link = "markdownH4" },
		markdownH5 = { fg = c.mgt2, bold = s.bold },
		markdownH5Delimiter = { link = "markdownH5" },
		markdownH6 = { fg = c.grn2, bold = s.bold },
		markdownH6Delimiter = { link = "markdownH6" },
		markdownLinkText = { link = "markdownUrl" },
		markdownUrl = { fg = c.fg, sp = c.blu2, underline = true },

		mkdCode = { fg = c.blu, italic = s.italic },
		mkdCodeDelimiter = { fg = c.cyn2 },
		mkdCodeEnd = { fg = c.blu },
		mkdCodeStart = { fg = c.blu },
		mkdFootnotes = { fg = c.blu },
		mkdID = { fg = c.blu, underline = true },
		mkdInlineURL = { link = "markdownUrl" },
		mkdLink = { link = "markdownUrl" },
		mkdLinkDef = { link = "markdownUrl" },
		mkdListItemLine = { fg = c.fg },
		mkdRule = { fg = c.subtle },
		mkdURL = { link = "markdownUrl" },
	}
end
