local util = require("blade.util")

local M = {}

function M.get(c, s)
	return {
		ColorColumn = { bg = c.overlay },
		Conceal = { fg = c.muted },
		CurSearch = { fg = c.bg, bg = c.ylw2 },
		Cursor = { fg = c.bg, bg = c.fg },
		lCursor = { fg = c.bg, bg = c.fg },
		CursorColumn = { bg = c.overlay },
		CursorLine = { bg = c.overlay },
		CursorLineNr = { fg = c.subtle },
		DiffAdd = { bg = c.grn, blend = 40 },
		DiffChange = { bg = c.cyn, blend = 30 },
		DiffDelete = { bg = c.red, blend = 30 },
		DiffText = { bg = c.ylw2, blend = 30 },
		diffAdded = { link = "DiffAdd" },
		diffChanged = { link = "DiffChange" },
		diffRemoved = { link = "DiffDelete" },
		Directory = { fg = c.cyn2, bold = s.bold },
		ErrorMsg = { fg = c.red, bold = s.bold },
		FloatBorder = { fg = c.mgt, bg = c.surface },
		FloatTitle = { fg = c.ylw2, bg = c.surface, bold = s.bold },
		FoldColumn = { fg = c.subtle },
		Folded = { fg = c.subtle },
		IncSearch = { link = "CurSearch" },
		LineNr = { fg = c.muted },
		MatchParen = { fg = c.cyn2, bg = c.cyn2, blend = 25 },
		ModeMsg = { fg = c.fg },
		MsgSeparator = { fg = c.fg, bg = c.surface },
		MoreMsg = { fg = c.cyn2 },
		NonText = { fg = c.muted },
		Normal = { fg = c.fg, bg = c.bg },
		NormalFloat = { bg = c.surface },
		NormalNC = { fg = c.fg, bg = s.dim_inactive and c._nc or c.bg },
		NvimInternalError = { link = "ErrorMsg" },
		Pmenu = { fg = c.fg, bg = c.overlay },
		-- PmenuMatch = { fg = c.mgt, bg = c.overlay },
		PmenuSel = { bg = c.hl2, bold = true },
		-- PmenuMatchSel = { fg = c.mgt, bg = c.hl2 },
		PmenuSbar = { fg = c.fg, bg = c.hl3 },
		PmenuThumb = { fg = c.fg, bg = c.hl3 },
		ComplHintMore = { fg = c.ylw2 },
		Question = { fg = c.ylw2 },
		QuickFixLine = { fg = c.fg, bg = c.hl2, bold = true },
		RedrawDebugClear = { fg = c.bg, bg = c.ylw2 },
		RedrawDebugComposed = { fg = c.bg, bg = c.grn },
		RedrawDebugRecompose = { fg = c.bg, bg = c.red },
		Search = { fg = c.bg, bg = c.ylw2 },
		SignColumn = { fg = c.muted },
		SpecialKey = { fg = c.muted },
		SpellBad = { sp = c.red, undercurl = true },
		SpellCap = { sp = c.ylw, undercurl = true },
		SpellLocal = { sp = c.cyn2, undercurl = true },
		SpellRare = { sp = c.grn, undercurl = true },
		StatusLine = { fg = c.subtle, bg = c.surface },
		StatusLineNC = { fg = c.muted, bg = c.surface },
		StatusLineTerm = { fg = c.subtle, bg = c.surface },
		StatusLineTermNC = { fg = c.bg, bg = c.grn, blend = 60 },
		Substitute = { link = "IncSearch" },
		TabLine = { fg = c.muted, bg = c.surface },
		TabLineFill = { bg = "NONE" },
		TabLineSel = { fg = c.bg, bg = c.cyn2, bold = s.bold },
		Title = { fg = c.ylw2, bold = true },
		VertSplit = { fg = c.blu },
		Visual = { bg = c.hl2 },
		VisualNOS = { bg = c.hl3 },
		WarningMsg = { fg = c.ylw2, bold = s.bold },
		WildMenu = { link = "IncSearch" },
		WinBar = { fg = c.subtle, bg = c.surface, blend = 60 },
		WinBarNC = { fg = c.muted, bg = c.surface, blend = 60 },
		WinSeparator = { fg = c.muted },

		DiagnosticError = { fg = c.red, undercurl = true },
		DiagnosticHint = { fg = c.cyn2 },
		DiagnosticInfo = { fg = c.blu2 },
		DiagnosticOk = { fg = c.grn2 },
		DiagnosticWarn = { fg = c.ylw2 },
		DiagnosticDefaultError = { link = "DiagnosticError" },
		DiagnosticDefaultHint = { link = "DiagnosticHint" },
		DiagnosticDefaultInfo = { link = "DiagnosticInfo" },
		DiagnosticDefaultOk = { link = "DiagnosticOk" },
		DiagnosticDefaultWarn = { link = "DiagnosticWarn" },
		DiagnosticFloatingError = { link = "DiagnosticError" },
		DiagnosticFloatingHint = { link = "DiagnosticHint" },
		DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
		DiagnosticFloatingOk = { link = "DiagnosticOk" },
		DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
		DiagnosticSignError = { link = "DiagnosticError" },
		DiagnosticSignHint = { link = "DiagnosticHint" },
		DiagnosticSignInfo = { link = "DiagnosticInfo" },
		DiagnosticSignOk = { link = "DiagnosticOk" },
		DiagnosticSignWarn = { link = "DiagnosticWarn" },
		DiagnosticUnderlineError = { sp = c.red, undercurl = true },
		DiagnosticUnderlineHint = { sp = c.cyn2, undercurl = true },
		DiagnosticUnderlineInfo = { sp = c.blu2, undercurl = true },
		DiagnosticUnderlineOk = { sp = c.grn2, undercurl = true },
		DiagnosticUnderlineWarn = { sp = c.ylw2, undercurl = true },
		DiagnosticVirtualTextError = { fg = c.red, bg = c.red, blend = 10 },
		DiagnosticVirtualTextHint = { fg = c.cyn2, bg = c.cyn, blend = 10 },
		DiagnosticVirtualTextInfo = { fg = c.blu2, bg = c.blu, blend = 10 },
		DiagnosticVirtualTextOk = { fg = c.grn2, bg = c.grn, blend = 10 },
		DiagnosticVirtualTextWarn = { fg = c.ylw2, bg = c.ylw, blend = 10 },

		Boolean = { fg = c.ylw2 },
		Character = { fg = util.blend(c.grn, c.grn2, 0.5) },
		Comment = { fg = c.muted, italic = s.italic },
		Conditional = { fg = c.cyn },
		Constant = { fg = c.ylw2 },
		Debug = { fg = c.ylw2 },
		Define = { fg = c.red },
		Delimiter = { fg = c.blu },
		-- Delimiter = { fg = c.blu },
		Error = { fg = c.red },
		Exception = { fg = c.cyn },
		Float = { fg = c.ylw2 },
		Function = { fg = c.cyn2 },
		Identifier = { fg = c.fg },
		Include = { fg = c.red },
		Keyword = { fg = c.cyn, italic = s.italic },
		Label = { fg = c.mgt },
		LspCodeLens = { fg = c.subtle },
		LspCodeLensSeparator = { fg = c.muted },
		LspInlayHint = { fg = c.muted, bg = c.muted, blend = 10 },
		LspReferenceRead = { bg = util.blend(c.hl2, c.overlay, 0.3) },
		LspReferenceText = { bg = util.blend(c.hl2, c.overlay, 0.3) },
		LspReferenceWrite = { bg = util.blend(c.hl2, c.overlay, 0.3) },
		Macro = { fg = c.red },
		Number = { fg = c.ylw2 },
		Operator = { fg = c.blu },
		PreCondit = { fg = c.red },
		PreProc = { link = "PreCondit" },
		Repeat = { fg = c.cyn },
		Special = { fg = c.red },
		SpecialChar = { link = "Special" },
		SpecialComment = { fg = c.red },
		Statement = { fg = c.cyn, bold = s.bold },
		StorageClass = { fg = c.blu2 },
		-- String = { fg = c.grn },
		String = { fg = util.blend(c.grn, c.grn2, 0.5) },
		Structure = { fg = c.blu2 },
		Tag = { fg = c.red },
		Todo = { fg = c.cyn2, bg = c.cyn, blend = 30 },
		Type = { fg = c.blu2 },
		TypeDef = { link = "Type" },
		Underlined = { fg = c.fg, underline = true },

		healthError = { fg = c.red },
		healthSuccess = { fg = c.grn },
		healthWarning = { fg = c.ylw2 },
	}
end

return M
